# Generated by Django 4.2.6 on 2023-10-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0003_alter_cohort_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
