# Generated by Django 4.2.6 on 2023-10-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0004_alter_cohort_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="name",
            field=models.CharField(default="Apus", max_length=255),
            preserve_default=False,
        ),
    ]
