# Generated by Django 4.2.6 on 2023-10-29 04:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0005_cohort_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cohort",
        ),
        migrations.DeleteModel(
            name="Pace",
        ),
    ]
