# Generated by Django 4.2.6 on 2023-10-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0001_initial"),
        ("tracks", "0006_delete_cohort_delete_pace"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trackcourse",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="trackcourse",
            name="drip_date",
        ),
        migrations.AddField(
            model_name="trackcourse",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.CreateModel(
            name="TrackCourseDrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("override", models.BooleanField(default=False)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cohorts.cohort"
                    ),
                ),
                (
                    "track_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_date",
                        to="tracks.trackcourse",
                    ),
                ),
            ],
        ),
    ]
