# Generated by Django 4.2.6 on 2023-10-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0007_alter_trackcourse_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackcourse",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_courses",
                to="tracks.track",
            ),
        ),
    ]
