# Generated by Django 4.2.6 on 2023-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0008_alter_trackcourse_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackcourse",
            name="follows_drip",
            field=models.BooleanField(default=True),
        ),
    ]
