# Generated by Django 4.2.6 on 2023-10-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0009_trackcourse_follows_drip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="courses",
        ),
        migrations.AlterField(
            model_name="trackcourse",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="tracks.track",
            ),
        ),
    ]
