# Generated by Django 4.2.6 on 2023-10-29 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_alter_coursemodule_unique_together"),
        ("tracks", "0010_remove_track_courses_alter_trackcourse_track"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trackcourse",
            unique_together={("track", "course")},
        ),
    ]
