# Generated by Django 4.2.6 on 2023-10-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0011_alter_trackcourse_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="code",
            field=models.CharField(default="Dev Track 300", max_length=255),
            preserve_default=False,
        ),
    ]
