version: '3.1'
services:
  code-runner:
    build: ./code-runner-api
    image: dstoffels/code-runner-api:1
    ports:
      - 4200:4200
    privileged: true
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
    - lms_data:/var/lib/postgresql/data

volumes:
  lms_data:
    name: dcc-lms