# Generated by Django 4.2.6 on 2023-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
