# Generated by Django 4.2.6 on 2023-10-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0001_initial"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursemodule",
            name="drip_date",
        ),
        migrations.RemoveField(
            model_name="coursemodule",
            name="override_drip",
        ),
        migrations.CreateModel(
            name="CourseModuleDrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("override", models.BooleanField(default=False)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cohorts.cohort"
                    ),
                ),
                (
                    "course_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drips",
                        to="courses.coursemodule",
                    ),
                ),
            ],
        ),
    ]
