# Generated by Django 4.2.6 on 2023-10-28 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_course_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(("role__name", "Student")),
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
