# Generated by Django 4.2.6 on 2023-10-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_coursemodule_drip_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodule",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_modules",
                to="courses.course",
            ),
        ),
    ]
