# Generated by Django 4.2.6 on 2023-11-13 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_studentcourse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentCourse",
        ),
    ]
