# Generated by Django 4.2.6 on 2023-11-14 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_delete_studentcourse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseModuleDrip",
        ),
    ]
