# Generated by Django 4.2.6 on 2023-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_coursemodule_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursemodule",
            name="follows_drip",
            field=models.BooleanField(default=True),
        ),
    ]
