# Generated by Django 4.2.6 on 2023-10-29 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_course_is_published_coursemodule_follows_drip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="title",
            new_name="name",
        ),
    ]
