# Generated by Django 4.2.6 on 2023-10-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_rename_title_course_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="modules",
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
            ),
        ),
    ]
