# Generated by Django 4.2.6 on 2023-10-29 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0003_module_is_published"),
        ("courses", "0007_remove_course_modules_alter_coursemodule_course"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursemodule",
            unique_together={("course", "module")},
        ),
    ]
