# Generated by Django 4.2.6 on 2023-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_alter_coursemodule_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="can_self_enroll",
            field=models.BooleanField(default=False),
        ),
    ]
