import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header/Header';
import ThemeRegistry from './ThemeRegistry';
import { AuthProvider } from '@/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<AuthProvider>
			<ThemeRegistry options={{ key: 'mui' }}>
				<html lang="en">
					<body className={inter.className}>
						{/* <Header /> */}
						<main>{children}</main>
					</body>
				</html>
			</ThemeRegistry>
		</AuthProvider>
	);
}
