# Generated by Django 4.2.6 on 2023-10-29 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="can_manage_classes",
            new_name="can_manage_cohorts",
        ),
    ]
