# Generated by Django 4.2.6 on 2023-11-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                ("hours_per_week", models.PositiveIntegerField(default=40)),
                ("flex_factor", models.FloatField(default=1.0)),
                ("days_per_week", models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("course_gap_days", models.PositiveIntegerField(default=7)),
                (
                    "pace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cohorts.pace"
                    ),
                ),
            ],
        ),
    ]
