# Generated by Django 4.2.6 on 2023-11-13 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cohorts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(("role__name", "Student")),
                related_name="cohorts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
