# Generated by Django 4.2.6 on 2023-11-13 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0003_alter_cohort_students"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cohort",
            old_name="track",
            new_name="program",
        ),
    ]
