# Generated by Django 4.2.6 on 2023-11-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0006_alter_cohort_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortcourse",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="cohorts.cohort",
            ),
        ),
        migrations.AlterField(
            model_name="cohortmodule",
            name="cohort_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="cohorts.cohortcourse",
            ),
        ),
    ]
