# Generated by Django 4.2.6 on 2023-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("course_hours", models.IntegerField(blank=True, default=0)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
