# Generated by Django 4.2.6 on 2023-10-29 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="courseHours",
            new_name="course_hours",
        ),
    ]
