# Generated by Django 4.2.6 on 2023-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0002_rename_coursehours_module_course_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
