# Generated by Django 4.2.6 on 2023-10-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedLabTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("resources", models.TextField(blank=True, default="")),
                ("language", models.CharField(max_length=255)),
                ("required", models.BooleanField(default=True)),
                ("points", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("order", models.PositiveIntegerField()),
                ("course_hours", models.FloatField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units",
                        to="modules.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExternalURL",
            fields=[
                (
                    "unit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="units.unit",
                    ),
                ),
                ("url", models.URLField()),
                ("load_in_new_tab", models.BooleanField(default=False)),
            ],
            bases=("units.unit",),
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "unit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="units.unit",
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
            ],
            bases=("units.unit",),
        ),
    ]
