# Generated by Django 4.2.6 on 2023-11-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(blank=True)),
                ("follows_drip", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("external_url", "External URL"),
                            ("lab", "Lab"),
                            ("assignment", "Assignment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="modules.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="units.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalURL",
            fields=[
                (
                    "unittype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="units.unittype",
                    ),
                ),
                ("url", models.URLField()),
                ("load_in_new_tab", models.BooleanField(default=False)),
            ],
            bases=("units.unittype",),
        ),
    ]
