# Generated by Django 4.2.6 on 2023-10-26 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0001_initial"),
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="modules.module",
            ),
        ),
    ]
