# Generated by Django 4.2.6 on 2023-10-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("units", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="units.unit",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="externalurl",
            name="unit_ptr",
        ),
        migrations.RemoveField(
            model_name="lab",
            name="unit_ptr",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="course_hours",
        ),
        migrations.AddField(
            model_name="unit",
            name="type",
            field=models.CharField(
                choices=[
                    ("external_url", "External URL"),
                    ("lab", "Lab"),
                    ("assignment", "Assignment"),
                ],
                default="external_url",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="externalurl",
            name="unittype_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="units.unittype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lab",
            name="unittype_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="units.unittype",
            ),
            preserve_default=False,
        ),
    ]
