# Generated by Django 4.2.6 on 2023-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("units", "0003_alter_labtask_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtask",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
