# Generated by Django 4.2.6 on 2023-10-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("units", "0003_unittype_rename_title_unit_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labtask",
            name="points",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="description",
        ),
        migrations.AddField(
            model_name="lab",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="unit",
            name="order",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
