# Generated by Django 4.2.6 on 2023-10-30 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0004_rename_title_module_name"),
        ("units", "0004_remove_labtask_points_remove_unit_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="module",
            field=models.ForeignKey(
                blank=True,
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="modules.module",
            ),
            preserve_default=False,
        ),
    ]
