# Generated by Django 4.2.6 on 2023-10-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("units", "0005_alter_unit_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="follows_drip",
            field=models.BooleanField(default=True),
        ),
    ]
