# Generated by Django 4.2.6 on 2023-10-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("units", "0006_unit_follows_drip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="type",
            field=models.CharField(
                choices=[
                    ("external_url", "External URL"),
                    ("lab", "Lab"),
                    ("assignment", "Assignment"),
                ],
                max_length=50,
            ),
        ),
    ]
