# Generated by Django 4.2.6 on 2023-11-13 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programcourse",
            old_name="track",
            new_name="program",
        ),
        migrations.AlterUniqueTogether(
            name="programcourse",
            unique_together={("program", "course")},
        ),
    ]
