# Generated by Django 4.2.6 on 2023-11-13 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0002_rename_track_programcourse_program_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programcoursedrip",
            old_name="track_course",
            new_name="program_course",
        ),
    ]
