# Generated by Django 4.2.6 on 2023-11-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0003_rename_track_course_programcoursedrip_program_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programcoursedrip",
            name="program_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="programs.programcourse"
            ),
        ),
    ]
