# Generated by Django 4.2.6 on 2023-11-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "unittype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="units.unittype",
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(default=0)),
            ],
            bases=("units.unittype",),
        ),
        migrations.CreateModel(
            name="LabTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True)),
                ("description", models.TextField()),
                ("resources", models.TextField(blank=True, default="")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("c#", "C#"),
                        ],
                        max_length=255,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("use_previous_code", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LabTaskAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(blank=True, default="")),
                ("messages", models.JSONField(blank=True, default=list)),
                ("hint", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_complete", models.BooleanField(default=False)),
            ],
        ),
    ]
