# Generated by Django 4.2.6 on 2023-10-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labtask",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("c#", "C#"),
                ],
                max_length=255,
            ),
        ),
    ]
