# Generated by Django 4.2.6 on 2023-11-13 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtaskattempt",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_task_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labtaskattempt",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="labs.labtask"
            ),
        ),
        migrations.AddField(
            model_name="labtask",
            name="lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="labs.lab",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labtaskattempt",
            unique_together={("task", "student")},
        ),
    ]
