# Generated by Django 4.2.6 on 2023-10-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0002_alter_labtask_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labtaskattempt",
            name="assistant_msgs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="labtaskattempt",
            name="code",
            field=models.TextField(blank=True),
        ),
    ]
