# Generated by Django 4.2.6 on 2023-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0004_alter_labtaskattempt_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labtaskattempt",
            old_name="assistant_msgs",
            new_name="hints",
        ),
        migrations.AddField(
            model_name="labtaskattempt",
            name="messages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
