# Generated by Django 4.2.6 on 2023-11-01 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0005_rename_assistant_msgs_labtaskattempt_hints_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labtaskattempt",
            name="hints",
        ),
    ]
