# Generated by Django 4.2.6 on 2023-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0006_remove_labtaskattempt_hints"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtaskattempt",
            name="hint",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="labtaskattempt",
            name="code",
            field=models.TextField(blank=True, default=""),
        ),
    ]
