# Generated by Django 4.2.6 on 2023-11-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0007_labtaskattempt_hint_alter_labtaskattempt_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtask",
            name="use_previous_code",
            field=models.BooleanField(default=False),
        ),
    ]
